esphome:
  name: "thermostat-test"
  platform: ESP8266
  board: d1_mini

  on_boot:
    priority: -100.0
    then:
      - switch.turn_on: dallas_power
      - lambda: "id(oled_contrast).publish_state(0.4);"

substitutions:
  room: Max Wohnzimmer # Room Name

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.2.198
    gateway: 192.168.2.1
    subnet: 255.255.255.0

logger:
  logs:
    sensor: none
    # dallas.sensor: none

api:
ota:

i2c:
  frequency: 400kHz

switch:
  - platform: gpio
    id: dallas_power
    name: "Dallas Power"
    pin:
      number: GPIO03

  - platform: template
    id: brightness
    optimistic: true

binary_sensor:

  - platform: gpio
    id: button
    pin:
      number: D4
      inverted: true
    on_click:
      - min_length: 1000ms
        max_length: 20000ms
        then:
          - switch.toggle: brightness

dallas:
  - pin: D3
    update_interval: 2s

sensor:
  - platform: template
    id: oled_contrast

  - platform: dallas
    id: internal_temperature
    address: 0xf101143d2badaa28

  - platform: rotary_encoder
    id: encoder
    pin_a:
      number: D6
      mode: INPUT_PULLUP
    pin_b:
      number: D7
      mode: INPUT_PULLUP
    on_clockwise:
      - if:
          condition:
            switch.is_on: brightness
          then:
            - sensor.template.publish:
                id: oled_contrast
                state: !lambda "return id(oled_contrast).state + 0.02;"
            - lambda: |-
                id(oled1).set_contrast( id(oled_contrast).state );
          else:
            - homeassistant.service:
                service: climate.set_temperature
                data:
                  temperature: !lambda "return id(btt_target_temp).state + 0.5;"
                  entity_id: climate.max_wz_heizung_smart

    on_anticlockwise:
      then:
        - if:
            condition:
              switch.is_on: brightness
            then:
              - sensor.template.publish:
                  id: oled_contrast
                  state: !lambda "return id(oled_contrast).state - 0.02;"
              - lambda: |-
                  id(oled1).set_contrast( id(oled_contrast).state);
            else:
              - homeassistant.service:
                  service: climate.set_temperature
                  data:
                    temperature: !lambda "return id(btt_target_temp).state - 0.5;"
                    entity_id: climate.max_wz_heizung_smart

  - platform: homeassistant
    id: btt_target_temp
    entity_id: climate.max_wz_heizung_smart
    attribute: temperature

text_sensor:

  - platform: homeassistant
    id: btt_heating_state
    entity_id: climate.max_wz_heizung_smart
    attribute: hvac_action

display:
  - platform: ssd1306_i2c
    id: oled1
    update_interval: 1.0s
    contrast: 0.4
    model: "SH1106 128x64"
    rotation: 180
    address: 0x3C
    lambda: |-
      it.print(64, 0,  id(font1), TextAlign::TOP_CENTER, "${room}");

      it.printf(64, 4, id(font2), TextAlign::TOP_CENTER, " %.1f°", id(internal_temperature).state);
      it.printf(128, 64, id(font3), TextAlign::BASELINE_RIGHT, "Ziel:  %.1f°", id(btt_target_temp).state);

      if (id(brightness).state) {it.image(1, 49, id(bulb));} 
      else if (id(btt_heating_state).state == "idle") {it.image(1, 49, id(home_thermometer));}
      else {id(ani_fire).next_frame(); it.image(1, 49, id(ani_fire));}

animation:
  - file: "_icons/thermostat/fire.gif"
    id: ani_fire
image:
  - file: "_icons/thermostat/home-thermometer.png"
    id: home_thermometer
  - file: "_icons/thermostat/lightbulb-on-outline.png"
    id: bulb
font:
  - file: "_fonts/refsan.ttf"
    id: font1
    size: 12
  - file: "_fonts/refsan.ttf"
    id: font2
    size: 42
  - file: "_fonts/refsan.ttf"
    id: font3
    size: 13
